#!/usr/bin/env python3
"""
populate_utility_files.py

Populate README.md, USAGE.md, and utils.py files in chapter directories by using independent template files.

The chapter information is provided by the JSON file generated by the web scraping scripts.

The template files are located in the `tools/utility_files/templates` directory.

The target chapter directories are located in the `chapters` directory.

Usage:
    python3 tools/utility_files/populate_utility_files.py
    python3 tools/utility_files/populate_utility_files.py --overwrite
    python3 tools/utility_files/populate_utility_files.py --dry-run

"""

from __future__ import annotations

import argparse
import json
import logging
import re
import unicodedata
from pathlib import Path
from typing import Any, Final
from datetime import datetime


PROJECT_ROOT: Final[Path] = Path(__file__).resolve().parents[2]

DEFAULT_CHAPTERS_DIR: Final[Path] = PROJECT_ROOT / "chapters"
DEFAULT_TEMPLATE_DIR: Final[Path] = PROJECT_ROOT / \
    "tools" / "utility_files" / "templates"

DEFAULT_JSON_CANDIDATE_FILE: Final[Path] = (
    PROJECT_ROOT / "tools" / "web_scraping" / "out" / "atbs3e_toc.json"
)

TEMPLATE_TO_OUTPUT: Final[dict[str, str]] = {
    "README.md.template": "README.md",
    "USAGE.md.template": "USAGE.md",
    "utils.py.template": "utils.py",
}
